#!/usr/bin/env zsh

set -eu

SCRIPT_DIR=${0:a:h}

cd ${SCRIPT_DIR}
if [ -d duckdb-data ]; then
	echo "duckdb-data already exists!"
	exit 0
fi

# Download
wget https://zenodo.org/records/11239473/files/duckdb-data.tar.xz
# Extract
tar xfJv duckdb-data.tar.xz
rm duckdb-data.tar.xz

