#!/usr/bin/env zsh

source ./INPUT_BASE_DIRECTORY
./exec-file-py --input-data $INPUT_BASE_DIRECTORY/one-thread-per-connection/one-thread-per-connection.duckdb --output $INPUT_BASE_DIRECTORY/one-thread-per-connection/output --plot plot-latencies.R --prefix "OTPC-"

