#!/usr/bin/env zsh

set -eu

SCRIPT_DIR=${0:a:h}

cd ${SCRIPT_DIR}/beder-patch
pipenv run python load.py ../data/redis-all-patches-load/ ../data/redis-all-patches-load/redis-all-patches-load.duckdb

cd ${SCRIPT_DIR}/beder
pipenv run python loader_redis_all_patches.py --benchmark ../data/redis-all-patches-load/ --output ../data/redis-all-patches-load/redis-all-patches-load-beder.duckdb

