#!/usr/bin/env zsh

set -eu

SCRIPT_DIR=${0:a:h}

cd ${SCRIPT_DIR}
if [ -f debian.img ]; then
	echo "VM already exists!"
	exit 0
fi

# Download
wget https://zenodo.org/api/records/11370684/draft/files/debian.img.tar.xz/content
# Extract
tar xfJv debian.img.tar.xz
rm debian.img.tar.xz

